name: Trigger Render Deployment
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy to Renderss
    if: "!contains(join(github.event.commits.*.message), '#skip')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main #consider using pin for dependabot auto update as
      - name: Create deployment
        uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          node-version: lts/Jod #optional
          cli-version: 2.2.0
  notify_discord:
    needs: [main]
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        if: success()
        uses: Ilshidur/action-discord@v2.0.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            âœ” Deployment succeeded!
            Status: ${{ needs.main.result }}
            Commit: ${{ github.sha }}
